export const REQUEST_TRIP_SORTER_DATA = 'REQUEST_TRIP_SORTER_DATA';
export const RECEIVE_TRIP_SORTER_DATA = 'RECEIVE_TRIP_SORTER_DATA';
export const SET_IS_SEARCH = 'SET_IS_SEARCH';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'